name: Aroma CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Grant execute permission for gradlew
      run: chmod +x build.sh
    - name: Build with Gradle
      run : ./build.sh 
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aromainstaller
        path: out/install_wizard-arm64.zip

    - name: upload to tg
      env:
        CHAT_ID: ${{ secrets.CHAT_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_URL: ${{ github.event.head_commit.url }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        TITLE: Dualboot Helper
      run: |
        if [ ! -z "${{ secrets.CHAT_ID }}" ] && [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
          export VERSION=$(git rev-list --count HEAD)
          bash $GITHUB_WORKSPACE/tg.sh out/install_wizard-arm64.zip
        else
          echo "Telegram bot token is undefined, please add it to repository secrets!"
          exit 1
        fi
